'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { createSupabaseBrowserClient } from '../../lib/supabase-browser';

type AnyRow=Record<string,any>;
type Ops=Record<string,AnyRow[]>;
type Dashboard={counts:Record<string,number>;profiles:AnyRow[];permissions:Record<string,string[]>};
const roleLabels:{[key:string]:string}={admin:'Administrator',staff:'Staff',coach:'Coach',client:'Client'};
const tabs=['Overview','Users','Clients','Coaches','Applications','Services','Offerings','Bookings','Finance','Payments','Risk & Disputes','Providers'];

export default function AdminPage(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [dashboard,setDashboard]=useState<Dashboard|null>(null),[ops,setOps]=useState<Ops>({}),[tab,setTab]=useState('Overview');
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(''),[busy,setBusy]=useState<string|null>(null),[search,setSearch]=useState(''),[currentUserId,setCurrentUserId]=useState('');
 async function load(){
  setLoading(true);setMessage('');
  const {data:userData,error:userError}=await supabase.auth.getUser();
  if(userError||!userData.user){window.location.href='/admin/login';return;}
  setCurrentUserId(userData.user.id);
  const {data:roleData,error:roleError}=await supabase.rpc('get_my_role');
  if(roleError){setMessage(`Account verification failed. ${roleError.message}`);setLoading(false);return;}
  if(roleData?.status && roleData.status!=='active'){setMessage('Your Staff/Admin account is not active.');setLoading(false);return;}
  if(roleData?.role!=='admin' && roleData?.role!=='staff'){setMessage('This account does not have Staff/Admin permissions.');setLoading(false);return;}
  const [{data:d,error:de},{data:o,error:oe}]=await Promise.all([supabase.rpc('admin_get_platform_dashboard'),supabase.rpc('admin_get_platform_operations')]);
  if(de||oe){setMessage((de||oe)?.message||'Administration data is unavailable.');setLoading(false);return;}
  setDashboard(d as Dashboard);setOps((o||{}) as Ops);setLoading(false);
 }
 useEffect(()=>{load()},[]);
 async function call(name:string,args:Record<string,any>,success:string){setBusy(name);setMessage('');const {error}=await supabase.rpc(name,args);setMessage(error?error.message:success);setBusy(null);await load();}
 async function signOut(){await supabase.auth.signOut();window.location.href='/admin/login';}
 const c=dashboard?.counts||{};
 const cards=[['Total users',c.users],['Clients',c.clients],['Coaches',c.coaches],['Staff',c.staff],['Administrators',c.admins],['Active coaches',c.active_coaches],['Applications',c.coach_applications],['Active services',c.active_services],['Bookings',c.bookings],['Transactions',c.transactions]];
 const filter=(rows:AnyRow[])=>rows.filter(r=>{if(!search.trim())return true;const q=search.toLowerCase();return Object.values(r).some(v=>String(v??'').toLowerCase().includes(q))});
 const btn=(active=false)=>({border:'1px solid #c8d9e8',borderRadius:9,padding:'9px 12px',background:active?'#0b5d9b':'#fff',color:active?'#fff':'#173b59',fontWeight:800,cursor:'pointer' as const});
 const cell={padding:'11px 8px',borderBottom:'1px solid #edf2f6',fontSize:13};
 function Table({rows,columns,actions}:{rows:AnyRow[],columns:string[],actions?:(r:AnyRow)=>ReactNode}){return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:900}}><thead><tr>{columns.map(x=><th key={x} style={{textAlign:'left',padding:'10px 8px',borderBottom:'2px solid #dbe6ef',fontSize:12,color:'#607487'}}>{x.replaceAll('_',' ')}</th>)}{actions&&<th style={{textAlign:'left',padding:'10px 8px',borderBottom:'2px solid #dbe6ef',fontSize:12}}>Actions</th>}</tr></thead><tbody>{filter(rows).map((r,i)=><tr key={String(r.id||i)}>{columns.map(k=><td key={k} style={cell}>{typeof r[k]==='boolean'?(r[k]?'Yes':'No'):String(r[k]??'—')}</td>)}{actions&&<td style={cell}>{actions(r)}</td>}</tr>)}</tbody></table>{filter(rows).length===0&&<p style={{padding:18,color:'#607487'}}>No records found.</p>}</div>}
 function Section({title,children,tools}:{title:string;children:ReactNode;tools?:ReactNode}){return <section style={{background:'#fff',border:'1px solid #d8e6f1',borderRadius:16,padding:20,marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap',marginBottom:14}}><h2 style={{margin:0,fontSize:20}}>{title}</h2>{tools}</div>{children}</section>}
 return <main style={{minHeight:'100vh',background:'radial-gradient(circle at 50% 0%,#f8fcff 0,#eef7ff 45%,#e6f3fc 100%)',color:'#09233f',padding:'36px 16px 70px'}}><div style={{maxWidth:1450,margin:'0 auto'}}>
  <header style={{background:'rgba(255,255,255,.9)',border:'1px solid #d8e6f1',borderRadius:22,padding:'24px 26px',boxShadow:'0 14px 40px rgba(0,60,100,.08)',display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',flexWrap:'wrap'}}><div><div style={{fontWeight:900,letterSpacing:'.08em',textTransform:'uppercase',color:'#1671b9'}}>CareerDev Global</div><h1 style={{fontSize:'clamp(2rem,5vw,3.3rem)',margin:'6px 0'}}>Platform Administration</h1><p style={{maxWidth:900,lineHeight:1.6,margin:0,color:'#527085'}}>One secure control center for users, clients, coaches, marketplace applications, services, bookings, payments, payouts, disputes and operational settings.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a href="/coach-admin" style={{...btn(),textDecoration:'none'}}>Coach Review</a><button onClick={load} style={btn()}>Refresh</button><button onClick={signOut} style={{...btn(),color:'#8a2d2d'}}>Sign out</button></div></header>
  {message&&<div style={{marginTop:16,padding:14,borderRadius:12,background:'#fff',border:'1px solid #c8d9e8',overflowWrap:'anywhere',boxShadow:'0 8px 25px rgba(0,60,100,.05)'}}>{message}</div>}
  {loading?<p style={{marginTop:28,textAlign:'center',color:'#527085'}}>Loading administration data…</p>:!dashboard?<p style={{marginTop:28,textAlign:'center',color:'#527085'}}>Administration data is unavailable.</p>:<>
   <div style={{display:'flex',gap:8,overflowX:'auto',padding:'20px 0 8px',position:'sticky',top:0,zIndex:5,background:'rgba(238,247,255,.94)',backdropFilter:'blur(8px)'}}>{tabs.map(t=><button key={t} onClick={()=>setTab(t)} style={{...btn(tab===t),whiteSpace:'nowrap'}}>{t}</button>)}</div>
   {tab==='Overview'&&<><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:10,marginTop:12}}>{cards.map(([label,value])=><div key={String(label)} style={{background:'#fff',borderRadius:14,padding:16,border:'1px solid #d8e6f1',boxShadow:'0 8px 24px rgba(0,60,100,.05)'}}><div style={{fontSize:11,color:'#607487'}}>{label}</div><strong style={{fontSize:26}}>{value??0}</strong></div>)}</section><Section title="Role permissions"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14}}>{Object.entries(dashboard.permissions).map(([r,ps])=><div key={r} style={{padding:15,border:'1px solid #e1ebf3',borderRadius:12}}><strong>{roleLabels[r]||r}</strong><ul style={{lineHeight:1.7,paddingLeft:18}}>{ps.map(x=><li key={x}>{x.replaceAll('_',' ')}</li>)}</ul></div>)}</div></Section></>}
   {tab==='Users'&&<Section title="User & access management" tools={<input placeholder="Search users…" value={search} onChange={e=>setSearch(e.target.value)} style={{padding:9,border:'1px solid #c8d9e8',borderRadius:9}}/>}><Table rows={ops.profiles||[]} columns={['full_name','email','role','status','country','timezone','created_at']} actions={p=><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><select disabled={p.id===currentUserId||busy==='admin_set_user_role'} value={p.role} onChange={e=>call('admin_set_user_role',{p_user_id:p.id,p_role:e.target.value},'User role updated.')} style={{padding:7,borderRadius:7,border:'1px solid #c8d9e8'}}><option value="client">Client</option><option value="coach">Coach</option><option value="staff">Staff</option><option value="admin">Administrator</option></select><select disabled={busy==='admin_update_profile_status'} value={p.status||'active'} onChange={e=>call('admin_update_profile_status',{p_user_id:p.id,p_status:e.target.value},'User status updated.')} style={{padding:7,borderRadius:7,border:'1px solid #c8d9e8'}}><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></select></div>}/></Section>}
   {tab==='Clients'&&<Section title="Client management"><Table rows={ops.clients||[]} columns={['name','email','status','created_at']} actions={p=><select disabled={busy==='admin_update_client_status'} value={p.status||'active'} onChange={e=>call('admin_update_client_status',{p_client_id:p.id,p_status:e.target.value},'Client status updated.')} style={{padding:7,borderRadius:7,border:'1px solid #c8d9e8'}}><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></select>}/></Section>}
   {tab==='Coaches'&&<Section title="Coach management"><Table rows={ops.coaches||[]} columns={['name','email','professional_title','application_status','verification_status','marketplace_status','active']} actions={p=><select disabled={busy==='admin_update_coach_marketplace_status'} value={p.marketplace_status||'pending_activation'} onChange={e=>call('admin_update_coach_marketplace_status',{p_coach_id:p.id,p_marketplace_status:e.target.value},'Coach marketplace status updated.')} style={{padding:7,borderRadius:7,border:'1px solid #c8d9e8'}}><option value="pending_activation">Pending activation</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></select>}/></Section>}
   {tab==='Applications'&&<Section title="Coach applications"><Table rows={ops.applications||[]} columns={['display_name','professional_title','country','timezone','application_status','agreements','created_at']} actions={p=><div style={{display:'flex',gap:6}}><button disabled={busy==='admin_review_coach_application'} style={btn()} onClick={()=>call('admin_review_coach_application',{p_application_id:p.id,p_decision:'approve',p_notes:'Approved from platform administration.'},'Coach application approved.')}>Approve</button><button disabled={busy==='admin_review_coach_application'} style={btn()} onClick={()=>call('admin_review_coach_application',{p_application_id:p.id,p_decision:'reject',p_notes:'Rejected from platform administration.'},'Coach application rejected.')}>Reject</button></div>}/></Section>}
   {tab==='Services'&&<Section title="Service catalogue"><Table rows={ops.services||[]} columns={['name','slug','category','price','currency','active','created_at']} actions={p=><button style={btn()} disabled={busy==='admin_update_service'} onClick={()=>call('admin_update_service',{p_service_id:p.id,p_name:p.name,p_category:p.category||'',p_description:p.description||'',p_price:Number(p.price||0),p_currency:p.currency||'NGN',p_active:!p.active},p.active?'Service deactivated.':'Service activated.')}>{p.active?'Deactivate':'Activate'}</button>}/></Section>}
   {tab==='Offerings'&&<Section title="Coach service offerings"><Table rows={ops.offerings||[]} columns={['coach_name','title','price','currency','duration_minutes','delivery_mode','active']} actions={p=><button style={btn()} disabled={busy==='admin_update_offering_status'} onClick={()=>call('admin_update_offering_status',{p_offering_id:p.id,p_active:!p.active},p.active?'Offering deactivated.':'Offering activated.')}>{p.active?'Deactivate':'Activate'}</button>}/></Section>}
   {tab==='Bookings'&&<Section title="Marketplace bookings"><Table rows={ops.bookings||[]} columns={['client_name','coach_name','start_at','end_at','timezone','status','created_at']} actions={p=><select disabled={busy==='admin_update_booking_status'} value={p.status} onChange={e=>call('admin_update_booking_status',{p_booking_id:p.id,p_status:e.target.value,p_notes:'Administrative status update.'},'Booking status updated.')} style={{padding:7,borderRadius:7,border:'1px solid #c8d9e8'}}><option value="requested">Requested</option><option value="confirmed">Confirmed</option><option value="declined">Declined</option><option value="cancelled">Cancelled</option><option value="completed">Completed</option></select>}/></Section>}
   {tab==='Finance'&&<><Section title="Transactions"><Table rows={ops.transactions||[]} columns={['booking_id','gross_amount','currency','payment_status','fulfillment_status','release_eligibility','provider_key','provider_reference','created_at']}/></Section><Section title="Coach payouts"><Table rows={ops.payouts||[]} columns={['coach_id','amount','currency','status','release_check_status','created_at']}/></Section></>}
   {tab==='Payments'&&<Section title="Payment transactions"><Table rows={ops.payments||[]} columns={['transaction_id','provider_key','reference','type','amount','currency','status','processed_at','created_at']}/></Section>}
   {tab==='Risk & Disputes'&&<><Section title="Disputes"><Table rows={ops.disputes||[]} columns={['transaction_id','category','reason','status','amount_at_risk','currency','created_at']}/></Section><Section title="Refund requests"><Table rows={ops.refunds||[]} columns={['transaction_id','amount','reason','status','requested_by','created_at']}/></Section></>}
   {tab==='Providers'&&<Section title="Payment providers"><Table rows={ops.providers||[]} columns={['provider_key','display_name','active','supported_currencies','supported_countries']} actions={p=><button style={btn()} disabled={busy==='admin_update_payment_provider_status'} onClick={()=>call('admin_update_payment_provider_status',{p_provider_id:p.id,p_active:!p.active},p.active?'Provider disabled.':'Provider enabled.')}>{p.active?'Disable':'Enable'}</button>}/><p style={{fontSize:12,color:'#607487',marginTop:14}}>Payment records and financial state are displayed for oversight. Provider credentials remain in Supabase Edge Function secrets and are never exposed here.</p></Section>}
  </>}
 </div></main>
}
