'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { createSupabaseBrowserClient } from '../../../lib/supabase-browser';
import './styles.css';

const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export default function CoachProfilePage(){
 const params=useParams<{coachId:string}>(); const [profile,setProfile]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const sb=createSupabaseBrowserClient();const {data,error}=await sb.rpc('get_public_coach_profile',{p_coach_id:params.coachId});if(!error&&data?.coach_id)setProfile(data);}finally{setLoading(false)}})()},[params.coachId]);
 if(loading)return <main className="profile-page"><div className="profile-shell"><p>Loading coach profile…</p></div></main>;
 if(!profile)return <main className="profile-page"><div className="profile-shell empty-profile"><h1>Coach profile unavailable</h1><p>This profile is not currently active in the CareerDev marketplace.</p><a href="/coach-matching">← Return to coach matching</a></div></main>;
 return <main className="profile-page"><header className="profile-header"><a href="/coach-matching">← Coach matching</a><a href="/">CareerDev Global</a></header><section className="profile-hero"><div className="avatar-large">{profile.display_name.split(/\s+/).map((x:string)=>x[0]).slice(0,2).join('').toUpperCase()}</div><div><p className="eyebrow">VERIFIED CAREER COACH</p><h1>{profile.display_name}</h1><p className="headline">{profile.headline||profile.professional_title||'Career coach'}</p><p>{profile.country||'Global'}{profile.timezone?` · ${profile.timezone}`:''}</p></div></section><section className="profile-grid"><div><article className="profile-card"><h2>About</h2><p>{profile.bio||profile.professional_bio||'Professional coaching support tailored to your goals.'}</p></article><article className="profile-card"><h2>Specializations</h2><div className="chips">{(profile.specializations||[]).map((x:string)=><span key={x}>{x}</span>)}</div></article><article className="profile-card"><h2>Professional background</h2><p>{profile.professional_bio||'A goal-focused coaching approach designed around the client’s needs and context.'}</p><div className="meta-row"><span>{profile.years_coaching?`${profile.years_coaching} years coaching`:'Verified coach'}</span><span>{(profile.languages||[]).join(' · ')||'Languages available on request'}</span></div></article></div><aside><article className="profile-card"><h2>Coaching formats</h2><div className="chips">{(profile.coaching_formats||[]).map((x:string)=><span key={x}>{x}</span>)}</div><div className="verified">✓ Verified marketplace profile</div></article><article className="profile-card"><h2>Availability</h2>{profile.availability?.length?<div className="availability-list">{profile.availability.map((a:any)=><div key={`${a.day_of_week}-${a.start_time}`}><strong>{days[a.day_of_week]}</strong><span>{String(a.start_time).slice(0,5)}–{String(a.end_time).slice(0,5)} · {a.timezone}</span></div>)}</div>:<p>Availability is currently being updated.</p>}<button className="booking-button" onClick={()=>alert('Booking will open when the CareerDev scheduling service is connected. Human choice remains final.')}>Request a coaching session</button></article><article className="profile-card"><h2>Credentials</h2>{profile.credentials?.length?<ul>{profile.credentials.map((x:string)=><li key={x}>{x}</li>)}</ul>:<p>Credentials available during coach review.</p>}</article></aside></section></main>;
}
