"use client";

import { useEffect, useMemo, useState } from "react";
import "./styles.css";
import { createSupabaseBrowserClient } from "../../lib/supabase-browser";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://ufmhrmzumqkjvaezrmxf.supabase.co";
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_8lIUCYbLzqp69RpZmE8ktA_56-doCVl";
const services = ["Professional CV Revamp","LinkedIn Profile Optimization","Cover Letter Development","Career Coaching","Executive Coaching","Leadership Coaching","Career Strategy Session","Career Intelligence Assessment","Professional Branding Package"];
const aiSystems = [["Career Discovery AI","Career goals, skills, gaps and direction","Testing"],["CV & LinkedIn AI","ATS positioning and professional branding","Coming next"],["Research & Opportunities AI","Jobs, scholarships and global opportunities","Coming next"],["Lead Generation AI","Qualified prospects and client discovery","Coming next"],["Sales & Proposal AI","Proposals, offers and conversion support","Coming next"],["Marketing & Content AI","Content planning and campaign intelligence","Coming next"],["CEO & Operations AI","Business intelligence and operational support","Coming next"]];
const categoryIcons = { education: "🎓", experience: "🏆", skills: "🧩", goals: "🧭", leadership: "🌟", roles: "🎯", gaps: "🔎", outcomes: "📊", request: "💬", service: "🛠️", evidence: "📄", analysis: "🧠", information: "❓", strategy: "🗺️", review: "👥", delivery: "🚀", feedback: "🔁", tracking: "📈" } as const;\nconst allowedTypes = ["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain"];

export default function CareerIntelligencePage(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [service,setService]=useState(services[0]),[request,setRequest]=useState(""),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[userEmail,setUserEmail]=useState(""),[authMode,setAuthMode]=useState<"signup"|"signin">("signup"),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[analysis,setAnalysis]=useState<any>(null),[selectedFile,setSelectedFile]=useState<File|null>(null),[processing,setProcessing]=useState<any>(null),[step,setStep]=useState(1);
 const question=useMemo(()=>service.includes("CV")?"What role, industry, or career direction should the CV target?":service.includes("LinkedIn")?"What professional opportunities do you want LinkedIn to attract?":service.includes("Coaching")?"What career or leadership outcome do you want to achieve?":"What specific outcome would make this service successful for you?",[service]);
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>setUserEmail(data.session?.user.email||""));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUserEmail(s?.user.email||""));return()=>data.subscription.unsubscribe()},[supabase]);
 const authenticate=async()=>{setLoading(true);setMessage("");const r=authMode==="signup"?await supabase.auth.signUp({email,password,options:{data:{full_name:fullName}}}):await supabase.auth.signInWithPassword({email,password});setLoading(false);if(r.error){setMessage(r.error.message);return}if(authMode==="signup"&&!r.data.session){setMessage("Account created. Check your email to confirm, then sign in.");setAuthMode("signin");return}setUserEmail(r.data.user?.email||email);setMessage("Secure account connection established.")};
 const uploadDocument=async(userId:string,requestId:string,file:File)=>{if(!allowedTypes.includes(file.type))throw new Error("Please upload a PDF, DOC, DOCX, or TXT document.");if(file.size>10*1024*1024)throw new Error("Documents must be 10 MB or smaller.");const path=`${userId}/${requestId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await supabase.storage.from("client-documents").upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const {data:client}=await supabase.from("clients").select("id").eq("profile_id",userId).single();if(!client)throw new Error("Client profile could not be found.");const ins=await supabase.from("documents").insert({client_id:client.id,request_id:requestId,document_type:"career_document",original_filename:file.name,storage_path:path,file_size:file.size,mime_type:file.type,version:1,status:"uploaded"}).select("id").single();if(ins.error)throw ins.error;const queued=await supabase.rpc("queue_document_processing",{p_document_id:ins.data.id});if(queued.error)throw queued.error;return ins.data.id};
 const createRequestAndAnalyze=async()=>{setLoading(true);setMessage("");setAnalysis(null);setProcessing(null);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Please create an account or sign in first.");const {data:newRequestId,error}=await supabase.rpc("create_client_service_request",{p_full_name:fullName||session.user.user_metadata?.full_name||"CareerDev Global Client",p_service_name:service,p_original_request:request,p_objective:request});if(error)throw error;let documentId:string|undefined;if(selectedFile)documentId=await uploadDocument(session.user.id,newRequestId,selectedFile);if(documentId){const p=await fetch(`${SUPABASE_URL}/functions/v1/careerdev-document-processor`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_KEY},body:JSON.stringify({document_id:documentId})});const pb=await p.json();if(!p.ok)throw new Error(pb.error||"Document processing failed");setProcessing(pb)}const response=await fetch(`${SUPABASE_URL}/functions/v1/careerdev-intake-engine-v2`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_KEY},body:JSON.stringify({request_id:newRequestId})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Career Intelligence analysis failed");setAnalysis(body);setStep(2);setMessage(documentId?"Your document was uploaded, processed, and submitted to the Career Intelligence engine.":"Career Intelligence analysis completed. Your next questions are ready.")}catch(e:any){setMessage(e?.message||"Something went wrong. Please try again.")}finally{setLoading(false)}};
 return <main className="ci-page">
 <section className="ci-hero"><div className="ci-container"><div className="ci-kicker">CAREERDEV GLOBAL AI CAREER INTELLIGENCE</div><h1>Your career journey, intelligently organized.</h1><p>Tell us what you need. CareerDev Global structures your request, analyzes career evidence, identifies information gaps, and prepares the right next steps—with a Career Coach remaining in control.</p><div className="ci-hero-actions"><a className="ci-primary" href="#intake">Start My Career Intelligence Profile</a><a className="ci-secondary" href="#systems">Explore the AI Systems</a></div></div></section>
 <section id="intake" className="ci-section"><div className="ci-container"><div className="ci-section-heading"><span>01</span><div><h2>Intelligent Client Intake</h2><p>No giant questionnaire. Your service request determines the questions.</p></div></div><div className="ci-grid"><div className="ci-card intake-card">
 {!userEmail&&<><div className="ci-mini-label">SECURE CLIENT ACCESS</div><h3>{authMode==="signup"?"Create your CareerDev account":"Welcome back"}</h3>{authMode==="signup"&&<><label>Full name</label><input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Your full name"/></>}<label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/><button className="ci-primary full" onClick={authenticate} disabled={loading}>{loading?"Connecting...":authMode==="signup"?"Create Secure Account":"Sign In"}</button><button className="ci-link" onClick={()=>setAuthMode(authMode==="signup"?"signin":"signup")}>{authMode==="signup"?"Already have an account? Sign in":"New to CareerDev Global? Create an account"}</button></>}
 {userEmail&&<div className="ci-authenticated">✓ Signed in securely as <strong>{userEmail}</strong></div>}<label>What service do you need?</label><select value={service} onChange={e=>setService(e.target.value)}>{services.map(s=><option key={s}>{s}</option>)}</select><label>Tell us what you want to achieve</label><textarea value={request} onChange={e=>setRequest(e.target.value)} placeholder="Describe your career need, target opportunity, deadline, or challenge..."/><div className="ci-upload"><label htmlFor="career-document">📎 <strong>Upload career documents</strong></label><small>CV, LinkedIn export, essays, job descriptions, certificates or portfolio evidence · PDF, DOC, DOCX, TXT · max 10 MB</small><input id="career-document" type="file" accept=".pdf,.doc,.docx,.txt" onChange={e=>setSelectedFile(e.target.files?.[0]||null)}/>{selectedFile&&<small>Selected: {selectedFile.name}</small>}</div><button className="ci-primary full" onClick={createRequestAndAnalyze} disabled={loading||!request.trim()}>{loading?"Processing securely...":"Analyze My Request"}</button>{message&&<div className="ci-message">{message}</div>}{processing&&<div className="ci-result"><strong>✓ Document processed</strong><small>{processing.chunk_count} text chunks · {processing.fact_count} career evidence candidates</small></div>}</div>
 <div className="ci-card"><div className="ci-mini-label">DYNAMIC QUESTION ENGINE</div><h3>{analysis?question:"What happens next?"}</h3>{!analysis?<ol className="ci-list"><li>Securely access your client account</li><li>Understand your service request</li><li>Upload and securely process career evidence</li><li>Identify information gaps</li><li>Ask only necessary follow-up questions</li><li>Build your Career Intelligence Profile</li></ol>:<div className="ci-question"><p>{question}</p><input placeholder="Your answer..."/><button className="ci-secondary" onClick={()=>setStep(Math.min(step+1,5))}>Save & Continue</button></div>}{analysis&&<div className="ci-result"><strong>AI intake run created</strong><small>{analysis.ai_run_id?`Run: ${analysis.ai_run_id}`:"Your request has entered the workflow."}</small></div>}<div className="ci-progress"><span style={{width:`${step*20}%`}}/></div><small>Step {step} of 5 · AI processes; human expertise validates consequential decisions.</small></div></div></div></section>
 <section className="ci-section soft" id="profile"><div className="ci-container"><div className="ci-section-heading"><span>02</span><div><h2>Career Intelligence Profile™</h2><p>One evolving career record supporting multiple CareerDev Global services.</p></div></div><div className="profile-grid">{[["education","Education"],["experience","Experience & Achievements"],["skills","Skills & Transferable Skills"],["goals","Career Goals"],["leadership","Leadership Experience"],["roles","Target Roles & Locations"],["gaps","Development Gaps"],["outcomes","Applications & Outcomes"]].map(([key,x])=><div className="profile-item" key={x}><b className="category-icon" aria-hidden="true">{categoryIcons[key as keyof typeof categoryIcons]}</b><span>{x}</span><em>Ready for intelligence</em></div>)}</div></div></section>
 <section className="ci-section" id="workflow"><div className="ci-container"><div className="ci-section-heading"><span>03</span><div><h2>End-to-End Career Delivery</h2><p>A controlled service workflow rather than disconnected AI outputs.</p></div></div><div className="workflow">{[["request","Client Request"],["service","Service & Objective"],["evidence","Documents & Evidence"],["analysis","AI Analysis"],["information","Information Gaps"],["strategy","Service Strategy"],["review","Human Review"],["delivery","AI Delivery"],["feedback","Client Feedback"],["tracking","Outcome Tracking"]].map(([key,x])=><div className="workflow-step" key={x}><strong className="category-icon" aria-hidden="true">{categoryIcons[key as keyof typeof categoryIcons]}</strong><span>{x}</span></div>)}</div></div></section>
 <section className="ci-section soft" id="systems"><div className="ci-container"><div className="ci-section-heading"><span>04</span><div><h2>Seven CareerDev Global AI Systems</h2><p>Built around the principle: <strong>AI Processes. Humans Decide.</strong></p></div></div><div className="systems-grid">{aiSystems.map(([n,d,s])=><article className="system-card" key={n}><div className="system-icon">✦</div><div><h3>{n}</h3><p>{d}</p><span className={s==="Testing"?"status testing":"status"}>{s}</span></div></article>)}</div></div></section>
 <section className="ci-section"><div className="ci-container"><div className="control-panel"><div><span className="ci-kicker">TRUST & GOVERNANCE</span><h2>Built for professional career services—not blind automation.</h2><p>Evidence provenance, verification, quality gates, human review, model/prompt governance, observability and AI cost controls are built into the platform.</p></div><div className="control-grid"><span>✓ Evidence grounded</span><span>✓ No fabrication</span><span>✓ Human review gates</span><span>✓ AI quality testing</span><span>✓ Usage & cost controls</span><span>✓ Outcome tracking</span></div></div></div></section>
 <footer className="ci-footer"><div className="ci-container"><strong>CareerDev Global</strong><span>Developing careers, leaders, and talents across borders.</span><a href="/">Back to main website</a></div></footer></main>;
}
