"use client";

import { useEffect, useMemo, useState } from "react";
import "./styles.css";
import { createSupabaseBrowserClient } from "../../lib/supabase-browser";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://ufmhrmzumqkjvaezrmxf.supabase.co";
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_8lIUCYbLzqp69RpZmE8ktA_56-doCVl";
const services = ["Professional CV Revamp","LinkedIn Profile Optimization","Cover Letter Development","Career Coaching","Executive Coaching","Leadership Coaching","Career Strategy Session","Career Intelligence Assessment","Professional Branding Package"];
const aiSystems = [["Career Discovery AI","Career goals, skills, gaps and direction","Testing"],["CV & LinkedIn AI","ATS positioning and professional branding","Coming next"],["Research & Opportunities AI","Jobs, scholarships and global opportunities","Coming next"],["Lead Generation AI","Qualified prospects and client discovery","Coming next"],["Sales & Proposal AI","Proposals, offers and conversion support","Coming next"],["Marketing & Content AI","Content planning and campaign intelligence","Coming next"],["CEO & Operations AI","Business intelligence and operational support","Coming next"]];
const categoryIcons = { education: "🎓", experience: "🏆", skills: "🧩", goals: "🧭", leadership: "🌟", roles: "🎯", gaps: "🔎", outcomes: "📊", request: "💬", service: "🛠️", evidence: "📄", analysis: "🧠", information: "❓", strategy: "🗺️", review: "👥", delivery: "🚀", feedback: "🔁", tracking: "📈" } as const;
const allowedTypes = ["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain"];

export default function CareerIntelligencePage(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [service,setService]=useState(services[0]),[request,setRequest]=useState(""),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[userEmail,setUserEmail]=useState(""),[authMode,setAuthMode]=useState<"signup"|"signin">("signup"),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[analysis,setAnalysis]=useState<any>(null),[selectedFile,setSelectedFile]=useState<File|null>(null),[processing,setProcessing]=useState<any>(null),[step,setStep]=useState(1);
 const question=useMemo(()=>service.includes("CV")?"What role, industry, or career direction should the CV target?":service.includes("LinkedIn")?"What professional opportunities do you want LinkedIn to attract?":service.includes("Coaching")?"What career or leadership outcome do you want to achieve?":"What specific outcome would make this service successful for you?",[service]);
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>setUserEmail(data.session?.user.email||""));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUserEmail(s?.user.email||""));return()=>data.subscription.unsubscribe()},[supabase]);
 const authenticate=async()=>{setLoading(true);setMessage("");const r=authMode==="signup"?await supabase.auth.signUp({email,password,options:{data:{full_name:fullName}}}):await supabase.auth.signInWithPassword({email,password});setLoading(false);if(r.error){setMessage(r.error.message);return}if(authMode==="signup"&&!r.data.session){setMessage("Account created. Check your email to confirm, then sign in.");setAuthMode("signin");return}setUserEmail(r.data.user?.email||email);setMessage("Secure account connection established.")};
 const uploadDocument=async(userId:string,requestId:string,file:File)=>{if(!allowedTypes.includes(file.type))throw new Error("Please upload a PDF, DOC, DOCX, or TXT document.");if(file.size>10*1024*1024)throw new Error("Documents must be 10 MB or smaller.");const path=`${userId}/${requestId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await supabase.storage.from("client-documents").upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const {data:client}=await supabase.from("clients").select("id").eq("profile_id",userId).single();if(!client)throw new Error("Client profile could not be found.");const ins=await supabase.from("documents").insert({client_id:client.id,request_id:requestId,document_type:"career_document",original_filename:file.name,storage_path:path,file_size:file.size,mime_type:file.type,version:1,status:"uploaded"}).select("id").single();if(ins.error)throw ins.error;const queued=await supabase.rpc("queue_document_processing",{p_document_id:ins.data.id});if(queued.error)throw queued.error;return ins.data.id};
 const createRequestAndAnalyze=async()=>{setLoading(true);setMessage("");setAnalysis(null);setProcessing(null);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Please create an account or sign in first.");const {data:newRequestId,error}=await supabase.rpc("create_client_service_request",{p_full_name:fullName||session.user.user_metadata?.full_name||"CareerDev Global Client",p_service_name:service,p_original_request:request,p_objective:request});if(error)throw error;let documentId:string|undefined;if(selectedFile)documentId=await uploadDocument(session.user.id,newRequestId,selectedFile);if(documentId){const p=await fetch(`${SUPABASE_URL}/functions/v1/careerdev-document-processor`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_KEY},body:JSON.stringify({document_id:documentId})});const pb=await p.json();if(!p.ok)throw new Error(pb.error||"Document processing failed");setProcessing(pb)}const response=await fetch(`${SUPABASE_URL}/functions/v1/careerdev-intake-engine-v2`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_KEY},body:JSON.stringify({request_id:newRequestId})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Career Intelligence analysis failed");setAnalysis(body);setStep(2);setMessage(documentId?"Your document was uploaded, processed, and submitted to the Career Intelligence engine.":"Career Intelligence analysis completed. Your next questions are ready.")}catch(e:any){setMessage(e?.message||"Something went wrong. Please try again.")}finally{setLoading(false)}};
 return <main className="ci-page">
 <header className="ci-topbar"><div className="ci-container ci-topbar-inner"><a className="ci-brand" href="/" aria-label="CareerDev Global home"><span className="ci-brand-mark">CD</span><span>CareerDev <b>Global</b></span></a><nav aria-label="Career Intelligence navigation"><a href="/">Home</a><a href="/coach-matching">Find a Coach</a><a href="/account" className="ci-nav-cta">Account</a></nav></div></header>
 <div className="ci-subnav"><div className="ci-container ci-subnav-inner"><span><span className="ci-live-dot"/>Career Intelligence Platform</span><div><a href="#intake">Start</a><a href="#profile">Profile</a><a href="#workflow">Workflow</a><a href="#systems">AI Systems</a></div></div></div>
 <section className="ci-hero"><div className="ci-container ci-hero-grid"><div><div className="ci-kicker">AI-POWERED CAREER PLATFORM</div><h1>Turn your career story into your next move.</h1><p>CareerDev Intelligence brings your goals, experience, skills and evidence into one guided workflow—so the platform can identify what matters next and a Career Coach can validate the path.</p><div className="ci-hero-actions"><a className="ci-primary" href="#intake">Start My Career Intelligence</a><a className="ci-secondary" href="#workflow">See How It Works</a></div><div className="ci-trust"><span>✓ Evidence-led</span><span>✓ Human-reviewed</span><span>✓ Secure workflow</span></div></div><aside className="ci-hero-panel" aria-label="Career Intelligence journey preview"><div className="ci-panel-label">CAREER INTELLIGENCE PROFILE™</div><div className="ci-panel-title">Your career, connected.</div><div className="ci-journey"><span>Goals</span><b>→</b><span>Evidence</span><b>→</b><span>Skills</span><b>→</b><span>Next Move</span></div><div className="ci-panel-metrics"><div><strong>01</strong><small>Request</small></div><div><strong>02</strong><small>Analyze</small></div><div><strong>03</strong><small>Personalize</small></div></div></aside></div></section>
 <section className="ci-section ci-section-intake" id="intake"><div className="ci-container"><div className="ci-section-heading"><span>01</span><div><div className="ci-overline">START HERE</div><h2>Your career intelligence workspace</h2><p>One focused intake. Your service need determines the questions, evidence and next steps.</p></div></div><div className="ci-grid"><div className="ci-card intake-card">
 {!userEmail&&<><div className="ci-mini-label">SECURE CLIENT ACCESS</div><h3>{authMode==="signup"?"Create your CareerDev account":"Welcome back"}</h3>{authMode==="signup"&&<><label htmlFor="full-name">Full name</label><input id="full-name" value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Your full name" autoComplete="name"/></>}<label htmlFor="ci-email">Email</label><input id="ci-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/><label htmlFor="ci-password">Password</label><input id="ci-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters" autoComplete={authMode==="signup"?"new-password":"current-password"}/><button className="ci-primary full" onClick={authenticate} disabled={loading}>{loading?"Connecting...":authMode==="signup"?"Create Secure Account":"Sign In"}</button><button className="ci-link" onClick={()=>setAuthMode(authMode==="signup"?"signin":"signup")}>{authMode==="signup"?"Already have an account? Sign in":"New to CareerDev Global? Create an account"}</button></>}
 {userEmail&&<div className="ci-authenticated">✓ Signed in securely as <strong>{userEmail}</strong></div>}<label htmlFor="ci-service">What service do you need?</label><select id="ci-service" value={service} onChange={e=>setService(e.target.value)}>{services.map(s=><option key={s}>{s}</option>)}</select><label htmlFor="ci-request">What are you trying to achieve?</label><textarea id="ci-request" value={request} onChange={e=>setRequest(e.target.value)} placeholder="Describe your career need, target opportunity, deadline, or challenge..."/><div className="ci-upload"><label htmlFor="career-document">📎 <strong>Upload career documents</strong></label><small>CV, LinkedIn export, essays, job descriptions, certificates or portfolio evidence · PDF, DOC, DOCX, TXT · max 10 MB</small><input id="career-document" type="file" accept=".pdf,.doc,.docx,.txt" onChange={e=>setSelectedFile(e.target.files?.[0]||null)}/>{selectedFile&&<small>Selected: {selectedFile.name}</small>}</div><button className="ci-primary full" onClick={createRequestAndAnalyze} disabled={loading||!request.trim()}>{loading?"Processing securely...":"Analyze My Request"}</button>{message&&<div className="ci-message" role="status">{message}</div>}{processing&&<div className="ci-result"><strong>✓ Document processed</strong><small>{processing.chunk_count} text chunks · {processing.fact_count} career evidence candidates</small></div>}</div>
 <div className="ci-card ci-next-card"><div className="ci-mini-label">INTELLIGENT QUESTION ENGINE</div><div className="ci-step-badge">STEP {step} OF 5</div><h3>{analysis?question:"A guided path, not a giant questionnaire."}</h3>{!analysis?<ol className="ci-list"><li><b>Understand</b><span>Your service and desired outcome.</span></li><li><b>Gather</b><span>Your evidence and career history.</span></li><li><b>Identify</b><span>Missing information and priorities.</span></li><li><b>Personalize</b><span>Questions relevant to your goal.</span></li><li><b>Prepare</b><span>A clear next step for delivery.</span></li></ol>:<div className="ci-question"><p>{question}</p><input aria-label="Career intelligence answer" placeholder="Your answer..."/><button className="ci-secondary" onClick={()=>setStep(Math.min(step+1,5))}>Save & Continue</button></div>}{analysis&&<div className="ci-result"><strong>AI intake run created</strong><small>{analysis.ai_run_id?`Run: ${analysis.ai_run_id}`:"Your request has entered the workflow."}</small></div>}<div className="ci-progress" aria-label={`Step ${step} of 5`}><span style={{width:`${step*20}%`}}/></div><small className="ci-helper">AI processes; human expertise validates consequential decisions.</small></div></div></div></section>
 <section className="ci-section soft" id="profile"><div className="ci-container"><div className="ci-section-heading"><span>02</span><div><div className="ci-overline">YOUR CAREER RECORD</div><h2>Career Intelligence Profile™</h2><p>Build one evolving record that can support multiple CareerDev Global services.</p></div></div><div className="profile-grid">{[["education","Education"],["experience","Experience & Achievements"],["skills","Skills & Transferable Skills"],["goals","Career Goals"],["leadership","Leadership Experience"],["roles","Target Roles & Locations"],["gaps","Development Gaps"],["outcomes","Applications & Outcomes"]].map(([key,x])=><div className="profile-item" key={x}><b className="category-icon" aria-hidden="true">{categoryIcons[key as keyof typeof categoryIcons]}</b><span>{x}</span><em>Ready for intelligence</em></div>)}</div></div></section>
 <section className="ci-section" id="workflow"><div className="ci-container"><div className="ci-section-heading"><span>03</span><div><div className="ci-overline">THE PLATFORM FLOW</div><h2>From career story to career action</h2><p>A controlled workflow instead of disconnected AI outputs.</p></div></div><div className="workflow">{[["request","Client Request"],["service","Service & Objective"],["evidence","Documents & Evidence"],["analysis","AI Analysis"],["information","Information Gaps"],["strategy","Service Strategy"],["review","Human Review"],["delivery","AI Delivery"],["feedback","Client Feedback"],["tracking","Outcome Tracking"]].map(([key,x],i)=><div className="workflow-step" key={x}><strong className="category-icon" aria-hidden="true">{categoryIcons[key as keyof typeof categoryIcons]}</strong><span>{x}</span><small>{String(i+1).padStart(2,"0")}</small></div>)}</div></div></section>
 <section className="ci-section soft" id="systems"><div className="ci-container"><div className="ci-section-heading"><span>04</span><div><div className="ci-overline">THE AI LAYER</div><h2>Seven CareerDev Global AI Systems</h2><p>Built around one principle: <strong>AI Processes. Humans Decide.</strong></p></div></div><div className="systems-grid">{aiSystems.map(([n,d,s])=><article className="system-card" key={n}><div className="system-icon" aria-hidden="true">✦</div><div><div className="system-topline"><span className="system-index">AI</span><span className={s==="Testing"?"status testing":"status"}>{s}</span></div><h3>{n}</h3><p>{d}</p></div></article>)}</div></div></section>
 <section className="ci-section ci-section-final"><div className="ci-container"><div className="control-panel"><div><span className="ci-kicker">TRUST & GOVERNANCE</span><h2>Professional AI with human accountability.</h2><p>Evidence provenance, verification, quality gates, human review, model governance, observability and AI cost controls are designed into the platform.</p><a className="ci-secondary" href="#intake">Start with your career goal →</a></div><div className="control-grid"><span>✓ Evidence grounded</span><span>✓ No fabrication</span><span>✓ Human review gates</span><span>✓ AI quality testing</span><span>✓ Usage & cost controls</span><span>✓ Outcome tracking</span></div></div></div></section>
 <footer className="ci-footer"><div className="ci-container"><div><strong>CareerDev Global</strong><span>Developing careers, leaders, and talents across borders.</span></div><div><a href="/">Home</a><a href="/account">Account</a><a href="/coach-matching">Find a Coach</a></div></div></footer></main>;
}
