import Link from "next/link";

export const metadata = {
  title: "Privacy Policy | CareerDev Global",
  description: "How CareerDev Global collects, uses, protects and manages personal information.",
};

const sections = [
  ["1. Who we are", "CareerDev Global provides career development, coaching, employability, leadership and talent-mobility services, including AI-enabled career intelligence. For privacy questions, contact hello@careerdevglobal.com."],
  ["2. Information we may collect", "Depending on the service you use, we may collect account and contact details, professional profile information, CVs and application materials, career goals and preferences, coaching or service information you choose to provide, communications, bookings, transaction information, technical information and feedback. We aim to collect information that is relevant to the service being provided."],
  ["3. How we use information", "We may use information to create and manage accounts, deliver career and coaching services, personalise career resources, facilitate client-coach interactions, process requests and payments, communicate with users, improve our services, maintain security, meet legal obligations and develop responsible AI-enabled features. We do not use personal information for a new incompatible purpose without appropriate notice or another valid legal basis."],
  ["4. AI and career intelligence", "CareerDev Global may use AI to support career exploration, document improvement, opportunity research, content generation, workflow assistance and career intelligence. AI-generated information is intended to support human decision-making, not replace professional judgment. We apply human-oversight, provenance, confidentiality, bias-awareness and role-boundary safeguards. Users should review important outputs before relying on them."],
  ["5. Coaches and client information", "Coaches should only access or use client information needed for an agreed service. Clients should avoid submitting highly sensitive information unless it is necessary for the service and the platform specifically requests it. Information shared during coaching remains subject to applicable confidentiality obligations and the limits described in our Conditions of Use and the coach's applicable professional obligations."],
  ["6. Sharing information", "We may share information with service providers that help us operate the platform, such as hosting, communications, scheduling, payment, analytics and security providers, where appropriate safeguards apply. We may also disclose information where required by law, to protect users or the platform, or as part of a lawful business transaction. We do not sell personal information as a general business practice."],
  ["7. Data security", "We use reasonable technical and organisational measures designed to protect information against unauthorised access, loss, misuse or alteration. No internet service can guarantee absolute security. If a material data incident occurs, we will follow applicable notification and response requirements."],
  ["8. Cookies and similar technologies", "The website may use cookies or similar technologies for essential operation, preferences, security, analytics or other clearly explained purposes. Where consent is required, users should be given an appropriate choice. Cookie controls should be separate from acceptance of general terms."],
  ["9. Retention", "We retain personal information only for as long as reasonably necessary for the purpose for which it was collected, to provide the requested service, resolve disputes, maintain appropriate records, comply with legal obligations or protect legitimate interests. Retention periods may differ by information type and service."],
  ["10. Your privacy rights", "Depending on applicable law, you may have rights to access, correct, update, delete, restrict or object to certain processing, request portability, withdraw consent where consent is the legal basis, and raise a complaint with a relevant data-protection authority. Contact us at hello@careerdevglobal.com to make a privacy request."],
  ["11. International processing", "CareerDev Global may use service providers or infrastructure located in countries other than the country where you live. Where applicable, we will use appropriate safeguards for international transfers and explain material changes to our processing practices."],
  ["12. Children and young people", "CareerDev Global services should be used in accordance with applicable age requirements and any required parent or guardian involvement. We do not knowingly request unnecessary personal information from children. Where a service is intended for a young person, we will apply appropriate safeguarding, privacy and consent procedures."],
  ["13. Changes to this policy", "We may update this Privacy Policy when our services, technology or legal obligations change. We will publish the updated version on this page and identify the effective date. Material changes will be communicated through appropriate channels where required."],
];

export default function PrivacyPolicyPage() {
  return <main className="legal-page"><section className="legal-hero"><span>LEGAL & TRUST</span><h1>Privacy Policy</h1><p>Your information deserves clarity, care and responsible handling.</p><small>Last updated: September 2026</small></section><div className="legal-layout"><aside className="legal-toc"><strong>On this page</strong>{sections.map(([title]) => <a key={title} href={`#${title.split(". ")[0]}`}>{title}</a>)}</aside><article className="legal-content"><div className="notice-card"><strong>In plain language:</strong> We collect information to provide and improve CareerDev Global services, protect our users, operate our platform and meet our legal obligations. We aim to collect only what we need and explain how it is used.</div>{sections.map(([title, text]) => { const id = title.split(". ")[0]; return <section id={id} key={title}><h2>{title}</h2><p>{text}</p></section>; })}<div className="legal-cta"><h2>Privacy questions?</h2><p>Contact our team before submitting a sensitive request or document.</p><a href="mailto:hello@careerdevglobal.com">hello@careerdevglobal.com</a></div><Link className="back-link" href="/">← Back to CareerDev Global</Link></article></div></main>;
}
