'use client';

import {useEffect,useMemo,useState} from 'react';
import {createSupabaseBrowserClient} from '../../lib/supabase-browser';
import './styles.css';

type Service={offering_id:string;service_id:string;coach_id:string;coach_name:string;coach_avatar_url:string|null;service_name:string;category:string;title:string;description:string|null;price:number|null;currency:string|null;duration_minutes:number;delivery_mode:string};

export default function BookServicePage(){
 const supabase=createSupabaseBrowserClient();const [items,setItems]=useState<Service[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [category,setCategory]=useState('All');
 useEffect(()=>{(async()=>{const {data,error}=await supabase.rpc('get_public_service_directory');if(error)setError(error.message);setItems((data||[]) as Service[]);setLoading(false)})()},[]);
 const categories=useMemo(()=>['All',...Array.from(new Set(items.map(x=>x.category).filter(Boolean)))],[items]);const filtered=category==='All'?items:items.filter(x=>x.category===category);
 return <main className="service-directory"><header className="service-header"><a href="/">CareerDev Global</a><nav><a href="/book-coaching">Book a Coaching Session</a><a href="/book-service" aria-current="page">Book a Service</a><a href="/account">My Account</a></nav></header><section className="service-hero"><p className="eyebrow">CAREERDEV GLOBAL SERVICES</p><h1>Book a Service</h1><p>Choose a service directly from an available coach. Clients can browse and select any bookable service without going through coach matching.</p><div className="service-actions"><a href="/book-coaching">Browse coaches →</a><a href="/coach-matching">Find a coach by goal →</a></div></section><section className="service-shell"><div className="service-heading"><div><p className="eyebrow">BOOKABLE SERVICES</p><h2>Choose what you need</h2></div><div className="category-tabs">{categories.map(c=><button type="button" key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>{loading?<div className="service-empty">Loading services…</div>:error?<div className="service-empty">{error}</div>:filtered.length===0?<div className="service-empty"><h3>No services are currently bookable.</h3><p>Please check back soon.</p></div>:<div className="service-grid">{filtered.map(s=><article className="service-card" key={s.offering_id}><div className="service-coach"><span className="service-avatar">{s.coach_avatar_url?<img src={s.coach_avatar_url} alt=""/>:s.coach_name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span><div><strong>{s.coach_name}</strong><span>Verified coach</span></div></div><p className="eyebrow">{s.category}</p><h3>{s.title}</h3>{s.service_name!==s.title&&<p className="service-name">{s.service_name}</p>}<p>{s.description||'A professional CareerDev Global service delivered by this coach.'}</p><div className="service-meta"><span>{s.duration_minutes} min</span><span>{s.delivery_mode}</span>{s.price!=null&&<strong>{s.currency} {s.price}</strong>}</div><a className="service-button" href={`/coach-profile/${s.coach_id}?offering=${encodeURIComponent(s.offering_id)}`}>Book this service →</a></article>)}</div>}</section></main>;
}
