'use client';

import {useEffect,useState} from 'react';
import {createSupabaseBrowserClient} from '../../lib/supabase-browser';
import './styles.css';

export default function ClientDashboard(){
 const supabase=createSupabaseBrowserClient(); const [user,setUser]=useState<any>(null); const [bookings,setBookings]=useState<any[]>([]); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true);
 async function load(){const {data:{user}}=await supabase.auth.getUser();setUser(user);if(!user){setLoading(false);return}const {data,error}=await supabase.from('client_marketplace_upcoming_bookings').select('*').order('requested_start',{ascending:true});if(error)setMessage(error.message);setBookings(data??[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function cancel(id:string){const reason=window.prompt('Reason for cancelling this booking request (optional):')||null;if(reason===null && !window.confirm('Cancel this booking request?'))return;setMessage('');const {error}=await supabase.rpc('cancel_marketplace_booking',{p_booking_id:id,p_reason:reason});if(error)setMessage(error.message);else{setMessage('Booking cancelled.');await load()}}
 if(loading)return <main className="client-dash"><div className="dash-card"><p>Loading your bookings…</p></div></main>;
 if(!user)return <main className="client-dash"><div className="dash-card"><h1>Client dashboard</h1><p>Please sign in to view and manage your coaching bookings.</p><a href="/login?next=/client-dashboard">Sign in →</a></div></main>;
 return <main className="client-dash"><div className="dash-wrap"><header><a href="/coach-matching">← Coach matching</a><span>CareerDev Global · Client dashboard</span></header><section className="dash-hero"><p>COACHING MARKETPLACE</p><h1>Your coaching sessions</h1><p>Track requests and confirmed sessions in one place.</p></section>{message&&<div className="dash-message">{message}</div>}<section className="dash-card"><h2>Upcoming bookings</h2>{bookings.length===0?<p>You have no upcoming coaching bookings. <a href="/coach-matching">Find a coach →</a></p>:<div className="booking-list">{bookings.map(b=><article className="booking-card" key={b.id}><div><strong>{b.service_title||'Coaching session'}</strong><p>with {b.coach_display_name}</p><p>{new Date(b.requested_start).toLocaleString()} · {b.timezone}</p><p>{b.duration_minutes} minutes · {b.delivery_mode||'Coaching'}</p>{b.price!=null&&<p>{b.currency} {b.price}</p>}</div><div><span className={`status status-${b.booking_status}`}>{b.booking_status}</span>{b.booking_status!=='cancelled'&&<button onClick={()=>cancel(b.id)}>Cancel request</button>}</div></article>)}</div>}</section><section className="dash-card"><h2>What happens next?</h2><ol><li>Your request is sent to the coach.</li><li>The coach confirms the requested time.</li><li>CareerDev notifications and reminders keep both sides informed.</li><li>Payment can be completed through the marketplace payment flow when enabled.</li></ol></section></div></main>
}
