'use client';

import {useEffect,useState} from 'react';
import {createSupabaseBrowserClient} from '../../lib/supabase-browser';

type Props={userId:string};
export default function ClientProfilePanel({userId}:Props){
 const supabase=createSupabaseBrowserClient();
 const [profile,setProfile]=useState<any>(null);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 async function load(){const {data}=await supabase.from('profiles').select('full_name,email,phone,country,timezone,bio,linkedin_url,avatar_url').eq('id',userId).maybeSingle();setProfile(data)}
 useEffect(()=>{load()},[userId]);
 const initials=(profile?.full_name||'Client').split(/\s+/).map((x:string)=>x[0]).slice(0,2).join('').toUpperCase();
 function field(k:string,v:string){setProfile((p:any)=>({...p,[k]:v}))}
 async function save(){setBusy(true);setMessage('');setError('');const {error:e}=await supabase.from('profiles').update({full_name:profile.full_name,phone:profile.phone,country:profile.country,timezone:profile.timezone,bio:profile.bio,linkedin_url:profile.linkedin_url}).eq('id',userId);if(e)setError(e.message);else setMessage('Profile updated successfully.');setBusy(false);await load()}
 async function uploadAvatar(){if(!file)return;setBusy(true);setMessage('');setError('');if(file.size>5*1024*1024){setError('Profile pictures must be 5 MB or smaller.');setBusy(false);return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Use JPG, PNG, or WEBP for your profile picture.');setBusy(false);return}const path=`${userId}/${crypto.randomUUID()}-${file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-')}`;const {error:ue}=await supabase.storage.from('avatars').upload(path,file,{contentType:file.type,upsert:false});if(ue){setError(`Upload failed: ${ue.message}`);setBusy(false);return}const {data:{publicUrl}}=supabase.storage.from('avatars').getPublicUrl(path);const {error:pe}=await supabase.from('profiles').update({avatar_url:publicUrl}).eq('id',userId);if(pe){await supabase.storage.from('avatars').remove([path]);setError(pe.message);setBusy(false);return}if(profile?.avatar_url){try{const oldPath=new URL(profile.avatar_url).pathname.split('/storage/v1/object/public/avatars/')[1];if(oldPath)await supabase.storage.from('avatars').remove([decodeURIComponent(oldPath)])}catch{}}setFile(null);const input=document.getElementById('client-avatar-file') as HTMLInputElement|null;if(input)input.value='';setMessage('Profile picture updated.');setBusy(false);await load()}
 return <section className="dash-card profile-account-card"><div className="account-heading"><div><p className="section-kicker">YOUR ACCOUNT</p><h2>Profile & profile picture</h2><p className="note">Keep your profile current so coaches have useful context before a session.</p></div><div className="profile-avatar">{profile?.avatar_url?<img src={profile.avatar_url} alt="Profile"/>:<span>{initials}</span>}</div></div><div className="avatar-controls"><label className="file-label">Choose profile picture<input id="client-avatar-file" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className="secondary-button" onClick={uploadAvatar} disabled={!file||busy}>{busy?'Saving…':'Upload picture'}</button></div><div className="form-grid profile-form"><label>Full name<input value={profile?.full_name??''} onChange={e=>field('full_name',e.target.value)}/></label><label>Email<input value={profile?.email??''} disabled/></label><label>Phone<input value={profile?.phone??''} onChange={e=>field('phone',e.target.value)}/></label><label>Country<input value={profile?.country??''} onChange={e=>field('country',e.target.value)}/></label><label>Timezone<input value={profile?.timezone??''} onChange={e=>field('timezone',e.target.value)}/></label><label>LinkedIn<input value={profile?.linkedin_url??''} onChange={e=>field('linkedin_url',e.target.value)}/></label><label className="wide">About you<textarea value={profile?.bio??''} onChange={e=>field('bio',e.target.value)} placeholder="Tell your coach a little about your goals or background."/></label></div>{(message||error)&&<div className={error?'dash-message profile-error':'dash-message'}>{error||message}</div>}<button onClick={save} disabled={busy}>{busy?'Saving…':'Save profile changes'}</button></section>
}
