'use client';
import {useEffect,useState} from 'react';
import {createSupabaseBrowserClient} from '../../lib/supabase-browser';

type QueueRow={application_id:string;coach_id:string|null;display_name:string;professional_title:string|null;country:string|null;timezone:string|null;application_status:string;verification_status:string|null;marketplace_status:string|null;onboarding_status:string|null;required_agreements_accepted:boolean;eligible_for_activation:boolean;activation_blockers:any;active_availability_count:number;semantic_profile_ready:boolean;profile_completion_pct:number};

function Status({children,ok=false}:{children:React.ReactNode;ok?:boolean}){return <span style={{display:'inline-flex',alignItems:'center',gap:6,padding:'5px 9px',borderRadius:999,background:ok?'#e8f7ee':'#fff4df',color:ok?'#176b3a':'#8a5a00',fontSize:12,fontWeight:800}}>{ok?'✓':'•'} {children}</span>}

export default function CoachAdminPage(){
 const supabase=createSupabaseBrowserClient();
 const[apps,setApps]=useState<QueueRow[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 async function load(){setLoading(true);const{data,error}=await supabase.rpc('admin_get_coach_marketplace_queue');if(error)setMessage(error.message);else setApps((data??[]) as QueueRow[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function review(id:string,decision:'approve'|'reject'){setMessage('');const{data,error}=await supabase.rpc('admin_review_coach_application',{p_application_id:id,p_decision:decision,p_notes:decision==='approve'?'Approved for marketplace onboarding.':'Application not approved at this stage.'});if(error)setMessage(error.message);else setMessage(JSON.stringify(data));await load()}
 async function activate(applicationId:string){try{setMessage('Checking activation eligibility…');const row=apps.find(x=>x.application_id===applicationId);if(!row?.coach_id)throw new Error('Approved coach record was not found.');const{data,error}=await supabase.rpc('admin_activate_coach',{p_coach_id:row.coach_id});if(error)throw error;setMessage(JSON.stringify(data))}catch(e){setMessage(e instanceof Error?e.message:String(e))}await load()}
 async function sync(applicationId:string){try{setMessage('Refreshing semantic profile…');const row=apps.find(x=>x.application_id===applicationId);if(!row?.coach_id)throw new Error('Approved coach record was not found.');const{data,error}=await supabase.functions.invoke('careerdev-coach-semantic-sync',{body:{coach_id:row.coach_id}});if(error)throw error;setMessage(JSON.stringify(data));await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 const counts={submitted:apps.filter(a=>a.application_status==='submitted').length,approved:apps.filter(a=>a.application_status==='approved').length,active:apps.filter(a=>a.marketplace_status==='active').length,blocked:apps.filter(a=>a.application_status==='approved'&&!a.eligible_for_activation).length};
 return <main style={{minHeight:'100vh',padding:'48px 24px',background:'#eef7ff',color:'#09233f'}}><div style={{maxWidth:1180,margin:'0 auto'}}>
  <p style={{fontWeight:700,letterSpacing:'.08em',textTransform:'uppercase',color:'#1671b9'}}>CareerDev Global</p><h1 style={{fontSize:'clamp(2rem,5vw,3.5rem)',margin:'8px 0'}}>Coach Marketplace Review</h1><p style={{maxWidth:780,lineHeight:1.7}}>Review applications, verify marketplace readiness, control activation and keep semantic profiles current. Public matching only sees approved, active and available coaches.</p>
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12,margin:'26px 0'}}>{[['Applications',apps.length],['Needs review',counts.submitted],['Approved',counts.approved],['Activation blockers',counts.blocked],['Marketplace active',counts.active]].map(([label,value])=><div key={String(label)} style={{background:'#fff',borderRadius:14,padding:'18px 20px',border:'1px solid #d8e6f1'}}><div style={{fontSize:13,color:'#5b7184'}}>{label}</div><strong style={{fontSize:28}}>{value}</strong></div>)}</section>
  {message&&<div style={{margin:'20px 0',padding:14,borderRadius:10,background:'#fff',border:'1px solid #c8d9e8',overflowWrap:'anywhere'}}>{message}</div>}
  {loading?<p>Loading marketplace readiness…</p>:apps.length===0?<div style={{background:'#fff',borderRadius:16,padding:28,marginTop:24}}>No coach applications yet.</div>:<div style={{display:'grid',gap:18,marginTop:24}}>{apps.map(a=><article key={a.application_id} style={{background:'#fff',borderRadius:16,padding:24,boxShadow:'0 8px 30px rgba(9,35,63,.08)'}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>{a.display_name}</h2><p style={{margin:'6px 0',fontWeight:700}}>{a.professional_title||'Professional title not supplied'}</p><p style={{margin:0,color:'#52697e'}}>{a.country||'Country not supplied'} · {a.timezone||'Timezone not supplied'}</p></div><strong style={{textTransform:'capitalize'}}>{String(a.application_status).replace('_',' ')}</strong></div>
   <div style={{display:'flex',flexWrap:'wrap',gap:8,marginTop:18}}><Status ok={a.verification_status==='verified'}>{a.verification_status||'verification pending'}</Status><Status ok={a.required_agreements_accepted}>{a.required_agreements_accepted?'agreements accepted':'agreements required'}</Status><Status ok={a.active_availability_count>0}>{a.active_availability_count} active availability slot{a.active_availability_count===1?'':'s'}</Status><Status ok={a.semantic_profile_ready}>{a.semantic_profile_ready?'semantic profile ready':'semantic profile missing'}</Status><Status ok={a.profile_completion_pct>=85}>{a.profile_completion_pct}% profile complete</Status></div>
   {a.activation_blockers?.length>0&&<div style={{marginTop:16,padding:12,borderRadius:10,background:'#fff8ea',color:'#795400'}}><strong>Activation blockers:</strong> {Array.isArray(a.activation_blockers)?a.activation_blockers.join(', '):JSON.stringify(a.activation_blockers)}</div>}
   {a.application_status!=='approved'&&a.application_status!=='rejected'&&<div style={{display:'flex',gap:10,marginTop:20}}><button onClick={()=>review(a.application_id,'approve')} style={{border:0,borderRadius:9,padding:'11px 18px',background:'#0b5d9b',color:'#fff',fontWeight:700}}>Approve</button><button onClick={()=>review(a.application_id,'reject')} style={{border:'1px solid #d2dce5',borderRadius:9,padding:'11px 18px',background:'#fff',color:'#8a2635',fontWeight:700}}>Reject</button></div>}
   {a.application_status==='approved'&&<div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:20}}><button onClick={()=>activate(a.application_id)} style={{border:0,borderRadius:9,padding:'11px 18px',background:'#0b5d9b',color:'#fff',fontWeight:700}}>Check eligibility &amp; activate</button><button onClick={()=>sync(a.application_id)} style={{border:'1px solid #c8d9e8',borderRadius:9,padding:'11px 18px',background:'#fff',color:'#0b5d9b',fontWeight:700}}>Refresh semantic profile</button></div>}
  </article>)}</div>}
 </div></main>}
