import Link from "next/link";

export const metadata = { title: "FAQ | CareerDev Global", description: "Frequently asked questions about CareerDev Global, clients, coaches and AI career intelligence." };

const faqs = [
  ["What is CareerDev Global?", "CareerDev Global is a career development and talent-mobility platform combining human expertise, coaching, professional services and AI-enabled career intelligence."],
  ["Who can use CareerDev Global?", "The platform is designed for clients seeking career development support and for qualified coaches and professionals who provide relevant services. Specific features may have eligibility or availability requirements."],
  ["What is Career Intelligence?", "Career Intelligence is a structured approach to understanding a person's goals, interests, capabilities, experience and opportunities, then translating that information into practical career options and actions. It is designed to support—not make—career decisions."],
  ["Can AI choose a career for me?", "No. AI can help you explore possibilities, identify patterns, organise information and generate questions or options. Your goals, values, context and judgment remain central to the decision."],
  ["Can I rely on AI-generated career or job information?", "AI outputs should be treated as assistance, not guaranteed facts. Check important information against authoritative or current sources, especially for deadlines, requirements, compensation, immigration, education or regulated professions."],
  ["How do I find a coach?", "Use the coach-discovery pathway when available, review the coach's profile and scope, and choose a professional whose expertise and approach fit your needs. Ask questions before starting if you need clarification."],
  ["What should I look for in a coach?", "Consider the coach's relevant experience, training, credentials, areas of practice, approach, availability and the type of support you want. Credentials should be verified through the relevant issuing body where appropriate."],
  ["Are CareerDev Global coaches employees?", "Not necessarily. Where the platform connects clients with independent coaches, the coach may operate as an independent professional. The applicable service description and coach profile should make the relationship clear."],
  ["What can the CV & LinkedIn service do?", "It can help improve structure, clarity, evidence, relevance, positioning and alignment with a target role or career direction. Users should review the final content and confirm that every claim is accurate."],
  ["Does CareerDev Global guarantee a job?", "No. Career outcomes depend on many factors outside the platform's control. CareerDev Global provides tools and support, not a guaranteed employment, admission, promotion or salary outcome."],
  ["What professional standards guide CareerDev Global?", "Relevant practices are informed by frameworks including ICF, IAEVG, NCDA, EMCC Global and NACE, with Mindler ICCC treated as a specialised career-coaching practice reference. Framework alignment does not by itself imply membership, accreditation, certification or endorsement."],
  ["Why is ICF prioritised?", "ICF provides a primary coaching ethics and competency reference for coaching-related workflows. Other frameworks are applied according to the type of service, so career guidance, employability and coaching needs can each receive appropriate safeguards."],
  ["How does CareerDev Global protect my information?", "We aim to collect information that is relevant to the service, use reasonable security measures and provide privacy information about how data is used. See the Privacy Policy for the detailed approach and available rights."],
  ["Can I delete or correct my information?", "Privacy rights depend on applicable law and the type of information. Contact hello@careerdevglobal.com with your request and we will direct it to the appropriate process."],
  ["What if I need professional help outside career coaching?", "Career coaching is not a substitute for clinical, legal, medical, financial or other specialist services. A coach or AI system should identify role boundaries and recommend appropriate specialist support where the issue falls outside their competence."],
  ["How do coaches use AI?", "AI may support preparation, organisation, drafting or research. Coaches remain responsible for professional judgment, client confidentiality, accuracy, boundaries and the quality of the service they provide."],
  ["How do I become a coach on the platform?", "Start with the coach pathway when available. Be prepared to provide accurate professional information, qualifications, areas of practice and other information required for profile review or onboarding."],
  ["What happens if I have a complaint?", "Contact hello@careerdevglobal.com with enough information for the team to understand the issue. We will route the matter to the appropriate support, service or review process."],
];

export default function FAQPage() {
  return <main className="faq-page"><section className="faq-hero"><span>ANSWERS, WITHOUT THE JARGON</span><h1>Frequently Asked Questions</h1><p>Clear answers about CareerDev Global, Career Intelligence, coaching, AI, privacy and getting started.</p></section><div className="faq-layout"><aside className="faq-nav"><a href="#general">General</a><a href="#clients">Clients</a><a href="#coaches">Coaches</a><a href="#ai">AI & Trust</a></aside><div className="faq-list"><div id="general" className="faq-group"><h2>General</h2>{faqs.slice(0,5).map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div><div id="clients" className="faq-group"><h2>For Clients</h2>{faqs.slice(5,10).map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div><div id="ai" className="faq-group"><h2>AI, Privacy & Professional Standards</h2>{faqs.slice(10,16).map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div><div id="coaches" className="faq-group"><h2>For Coaches</h2>{faqs.slice(16).map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div><div className="faq-cta"><h2>Still have a question?</h2><p>We are happy to help you find the right information.</p><a href="mailto:hello@careerdevglobal.com">Contact CareerDev Global →</a><Link href="/help-center">Visit Help Center</Link></div></div></div></main>;
}
